version: '3.9'
services:
  db:
    image: abuiliazeed/postgresmultidb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: storefrontdb,storefrontdbtest
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'

volumes:
  pgdata: